name: Build CHIP-8 Emulator

on:
  push:
    branches: [ "main" ]

jobs:
  # MAC BUILD
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Install Raylib
        run: brew install raylib

      - name: Compile Mac Version
        run: g++ -std=c++17 main.cpp chip8.cpp platform.cpp -o chip8-mac -I$(brew --prefix)/include -L$(brew --prefix)/lib -lraylib

      - name: Upload Finished App
        uses: actions/upload-artifact@v4
        with:
          name: Mac-Emulator
          path: chip8-mac

  # WINDOWS BUILD
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Setup Windows C++ Environment (MSYS2)
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-raylib

      - name: Compile Windows Version
        shell: msys2 {0}
        run: g++ -std=c++17 main.cpp chip8.cpp platform.cpp -o chip8-windows.exe -lraylib -lgdi32 -lwinmm -lcomdlg32

      - name: Upload Finished .exe
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Emulator
          path: chip8-windows.exe

  # LINUX BUILD
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Install System Graphics & Audio Headers
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev

      - name: Compile and Install Raylib from Source
        run: |
          git clone --depth 1 https://github.com/raysan5/raylib.git
          cd raylib/src
          make PLATFORM=PLATFORM_DESKTOP
          sudo make install

      - name: Compile Linux Version
        run: g++ -std=c++17 main.cpp chip8.cpp platform.cpp -o chip8-linux -lraylib -lGL -lm -lpthread -ldl -lrt -lX11

      - name: Upload Finished App
        uses: actions/upload-artifact@v4
        with:
          name: Linux-Emulator
          path: chip8-linux
